[package]
name = "csync_misc"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
libc = "0.2"
log = "0.4"
pad = "0.1"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1"
toml = "0.8"
file-lock = "2.1"
tokio = { version = "1.43", features = ["full"] }
fern = { version = "0.7", features = ["colored"] }
humantime = "2.1"
openssl = "0.10"
chrono = "0.4"
base64 = "0.22"
aes-gcm = "0.10"
pbkdf2 = "0.12"
sha2 = "0.10"

[dev-dependencies]
once_cell = "1.20"
