namespace: "default"

image: "fioncat/csync:latest"

port: 13577
ssl: false

resources:
  requests:
    cpu: "500m"
    memory: "300Mi"
  limits:
    cpu: "2000m"
    memory: "1G"

pvc:
  storageClass: "ssd"
  size: "20Gi"
  accessModes: ["ReadWriteOnce"]

service:
  annotations: {}
  type: ClusterIP

config: {}
