csyncd:
  include: ["get-image-name"]
  env:
    - name: IMAGE_NAME
      value: csyncd

  steps:
    - name: Build image
      docker_build:
        image: "${IMAGE_NAME}"
        file: "csyncd/Dockerfile"

    - name: Push image
      docker_push: "${IMAGE_NAME}"

get-image-name:
  steps:
    - name: Get tag
      run: echo dev-$(git rev-parse --short HEAD)
      capture_output: IMAGE_TAG

    - name: Set image name
      set_env:
        name: IMAGE_NAME
        value: "fioncat/${IMAGE_NAME}:${IMAGE_TAG}"

    - name: Show image
      run: "echo Image is: ${IMAGE_NAME:?}"
