[package]
name = "csync"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.81"
bincode = "1.3.3"
bytes = "1.5.0"
clap = { version = "4.5.3", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
gethostname = "0.4.3"
log = "0.4.21"
pbkdf2 = "0.12.2"
serde = { version = "1.0.197", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
toml = "0.8.12"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.3.1", features = ["build", "rustc"] }

[profile.release]
lto = true
strip = true
incremental = false
