[package]
name = "csync"
version = "0.5.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/csync"
description = "Share your clipboard between different devices"

[dependencies]
actix-web = { version = "4.9.0", features = ["openssl"] }
aes-gcm = "0.10.3"
anyhow = "1.0.95"
async-trait = "0.1.84"
base64 = "0.22.1"
chrono = "0.4.39"
clap = { version = "4.5.24", features = ["derive"] }
console = "0.15.10"
fern = { version = "0.7.1", features = ["colored"] }
file-lock = "2.1.11"
humantime = "2.1.0"
jsonwebtoken = "9.3.0"
libc = "0.2.169"
log = "0.4.22"
openssl = "0.10.68"
pad = "0.1.6"
pbkdf2 = "0.12.2"
rand = "0.8.5"
reqwest = { version = "0.12.12", features = ["json"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
sd-notify = "0.4.3"
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
sha2 = "0.10.8"
shellexpand = "3.1.0"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
toml = "0.8.19"

[build-dependencies]
simple-error = "0.3.1"
vergen = { version = "9.0.2", features = ["build", "rustc", "cargo", "si"] }

[profile.release]
lto = true
strip = true
incremental = false
