[package]
name = "csync"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.2"
anyhow = "1.0.71"
arboard = "3.2.0"
atoi = "2.0.0"
bytes = "1.4.0"
clap = { version = "4.2.7", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.10.0"
human_bytes = "0.4.2"
log = "0.4.17"
sha256 = "1.1.3"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features=["full"] }
