[package]
name = "csync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
arboard = "3.2.0"
bincode = "1.3.3"
clap = { version = "4.2.7", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.10.0"
human_bytes = "0.4.2"
indicatif = "0.17.3"
log = "0.4.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_yaml = "0.9.21"
sha256 = "1.1.3"
tokio = { version = "1.28.1", features=["full"] }
