[package]
name = "csync"
version = "0.4.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/csync"
description = "Share your clipboard between different devices"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.93"
bincode = "1.3.3"
blake3 = "1.5.4"
bytes = "1.8.0"
clap = { version = "4.5.21", features = ["derive"] }
dirs = "5.0.1"
fern = { version = "0.7.0", features = ["colored"] }
humantime = "2.1.0"
log = "0.4.22"
pbkdf2 = "0.12.2"
serde = { version = "1.0.215", features = ["derive"] }
sha2 = "0.10.8"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "9.0.1", features = ["build", "rustc", "cargo", "si"] }

[profile.release]
lto = true
strip = true
incremental = false
