apiVersion: v1
kind: ConfigMap
metadata:
  name: csync-config
  namespace: "{{ .Values.namespace }}"
data:
  server.toml: |
    bind = "0.0.0.0:{{ .Values.port }}"
    ssl = {{ .Values.ssl }}
    {{- toToml .Values.config | nindent 4 }}
