apiVersion: v1
kind: ConfigMap
metadata:
  name: csync-config
  namespace: "{{ .Values.namespace }}"
data:
  server.toml: |
    bind = "0.0.0.0:{{ .Values.port }}"
    ssl = {{ .Values.ssl }}
    admin_password = "{{ .Values.admin_password }}"
    {{- toToml .Values.config | nindent 4 }}

  client.toml: |
    server = "{{ ternary "https" "http" .Values.ssl }}://127.0.0.1:{{ .Values.port }}"
    accept_invalid_certs = true
    username = "admin"
    password = "{{ .Values.admin_password }}"
