apiVersion: v1
kind: ConfigMap
metadata:
  name: csync-config
  namespace: "{{ .Values.namespace }}"
data:
  server.toml: |
    bind = "0.0.0.0:{{ .Values.port }}"
    ssl = {{ .Values.ssl }}
    admin_password = "{{ .Values.admin_password }}"
    recycle_hours = {{ .Values.config.recycleHours }}
    truncate_text_width = {{ .Values.config.truncateTextWidth }}
    salt_length = {{ .Values.config.saltLength }}
    token_expiration_secs = {{ .Values.config.tokenExpirationSecs }}
    keep_alive_secs = {{ .Values.config.keep_alive_secs }}
    workers = {{ .Values.config.workers }}
    payload_limit_mib = {{ .Values.config.payloadLimitMib }}

  client.toml: |
    server = "{{ ternary "https" "http" .Values.ssl }}://127.0.0.1:{{ .Values.port }}"
    accept_invalid_certs = true
    username = "admin"
    password = "{{ .Values.admin_password }}"
