apiVersion: v1
kind: Secret
metadata:
  name: csync-pki
  namespace: "{{ .Values.namespace }}"
data:
  token_private.pem: {{ .Files.Get "pki/token_private.pem" | b64enc }}
  token_public.pem: {{ .Files.Get "pki/token_public.pem" | b64enc }}
{{- if .Values.ssl }}
  cert.pem: {{ .Files.Get "pki/cert.pem" | b64enc }}
  key.pem: {{ .Files.Get "pki/key.pem" | b64enc }}
{{- end}}
