[package]
name = "csyncd"
edition = "2021"
description = "Csync daemon"

[dependencies]
tauri = { version = "2.2", features = ["tray-icon"] }
tauri-plugin-shell = { version = "2.2" }

[build-dependencies]
csync_build = { path = "../build" }
tauri-build = { version = "2.0", features = [] }
