server = "127.0.0.1:7703"
device = "device-0"
password = "test password 123"

watch = ["device-1"]

[read]
cmd = ["wl-paste", "--no-newline"]
interval = 200

[write]
text_cmd = ["wl-copy"]
download_image = true
