name: csyncd-image

on:
  push:
    tags:
      - '*'

jobs:
  build-csyncd-image:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed -e "s/^v//")

      - name: Build the image
        run: docker build -f csyncd/Dockerfile -t fioncat/csync:${{ steps.get_version.outputs.VERSION }} .

      - name: Push the image
        run: docker push fioncat/csync:${{ steps.get_version.outputs.VERSION }}
