name: Release Binary

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create
        uses: softprops/action-gh-release@v2
        with:
          draft: true

  release-binary:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps for ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          archive: csync-$target
          bin: csync-server,csyncd,csynctl
          tar: unix
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
