name: release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Installing Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install libx11-xcb-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: csync
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
